version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=flashcards
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=flashcards
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=flashcardsadmin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=rootflashcards
    ports:
      - 5050:80
